version: '3'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes:
      - DB:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306"
    networks:
      - inception-network

  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
    container_name: wordpress
    restart: always
    volumes:
      - WordPress:/var/www/wordpress
    ports:
      - "9000"
    networks:
      - inception-network
    env_file:
      - .env

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - WordPress:/var/www/wordpress
    networks:
      - inception-network
    depends_on:
      - wordpress
    env_file:
      - .env

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    restart: always
    env_file:
      - .env
    networks:
      - inception-network
    depends_on:
      - nginx
    ports:
      - "4848:4848"

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    restart: always
    depends_on:
      - mariadb
    networks:
    - inception-network
    ports:
      - "8080:8080"
  
  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server/
    restart: always
    env_file: .env
    networks:
      - inception-network
    depends_on:
      - nginx
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
  
  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer/
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception-network
    ports:
      - "9443:9443"

  site:
    container_name: site
    build: requirements/bonus/site/
    restart: always
    networks:
      - inception-network
    depends_on:
      - nginx
    ports:
      - "1111:1111"
  
networks:
  inception-network:
    driver: bridge

volumes:
  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/iyapar/data/wordpress'

  DB:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/iyapar/data/db'

  